services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"  

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.2
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_FEATURES: scripts
      KC_HTTP_RELATIVE_PATH: /auth
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./apps/api/keycloak/realms:/opt/keycloak/data/import
    depends_on:
      postgres:
        condition: service_healthy
    command: 
      - start-dev 

volumes:
  keycloak_data:
  postgres_data: