services:
  postgres:
    image: postgres:alpine
    container_name: treviaz
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRESQL_DATABASE: treviaz
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
