import '@treviaz/ui/globals.css'

import { env } from '@treviaz/env'
import type { Metadata } from 'next'

import { Providers } from './providers'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning={env.NEXT_PUBLIC_NODE_ENV === 'development'}
    >
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
